### ISSUE TITLE
Rstudio

### ISSUE THREAD

**Issue by g2cordr** [gejujoal/CarEvaluation2018#2]
Descarga e instalación de Rstudio para análisis de datos

**Comment by Juancbailon** [comment]
Para poder descargar RStudio se puede acceder al siguiente enlace:
https://www.rstudio.com/products/rstudio/download/

**Comment by g2cordr** [comment]
Descargado e instalado.
dejo enlace a hoja de comandos básicos
[Cheat Sheets RStudio](https://www.rstudio.com/resources/cheatsheets/)
