### ISSUE TITLE
Análisis del dataset para posteriores estudios

### ISSUE THREAD

**Issue by Juancbailon** [gejujoal/CarEvaluation2018#3]
Sobre el dataset escogido se ha de realizar un pequeño estudio sobre los diferentes análisis que se pueden llevar a cabo

**Comment by Juancbailon** [comment]
Para cada coche el daaset presenta las siguientes características: 

-  buying: v-high, high, med, low
-maint: v-high, high, med, low
-doors: 2, 3, 4, 5-more
-persons:  2, 4, more
-lug_boot: small, med, big
-safety: low, med, high

A priori se podría analizar la distribución de cada atributo y representarlo gráficamente ¿ Alguna idea más?

**Comment by jose-lj** [comment]
Se podría analizar si existe relación entre la categoría de seguridad y el valor de adquisición
