### ISSUE TITLE
Como leer datos en R

### ISSUE THREAD

**Issue by g2cordr** [gejujoal/CarEvaluation2018#4]
Como leer datos en R

**Comment by Juancbailon** [comment]
Para poder obtener los datos de trabajo desde R tan solo es necesario ejecutar los siguientes comandos:
car_data <- read.table( "http://archive.ics.uci.edu/ml/machine-learning-databases/car/car.data", sep=",", header=FALSE)
#Nombrar las columnas de acuerdo con la documentación
colnames(car_data) <- c("buying","maint","doors","persons","lug_boot","safety","class")

**Comment by g2cordr** [comment]
Ok. comprobado.
